#!/usr/bin/env python3
"""
run_scoring.py

Orchestrates the scoring of candidate sites using the Full Grid method.
Adapted for the new score.py architecture.
"""

import numpy as np
from score import rank_candidates_full_grid

def main():
    # -----------------------------
    # 1. Configuration
    # -----------------------------
    input_file = "authorized_points_all_masks.npz"
    output_file = "scored_candidates_fullgrid.npz"
    terrain_file = "terrain_mat.npz"

    radar_height_agl_m = 20.0
    
    # Standard Flight Levels for assessment
    flight_levels = [5, 10, 20, 50, 100, 200, 300, 400]

    # Simulation precision
    n_samples = 100   # Number of sample points along each ray
    margin_m = 0.0    # Safety margin for LOS

    # -----------------------------
    # 2. Load Authorized Candidates
    # -----------------------------
    print(f"--- Loading candidates from {input_file} ---")
    try:
        data = np.load(input_file)
        # Handle the format generated by the previous script (separate arrays)
        lats = data["lat"]
        lons = data["lon"]
        n_points = len(lats)
        print(f"✓ Found {n_points:,} authorized candidates.")
    except FileNotFoundError:
        print(f"Error: {input_file} not found. Run the masks script first.")
        return

    # Limit for testing (set to None for all points)
    # K = 10  # Uncomment to test only the first 10 points
    K = n_points 
    
    # Prepare list of candidates for the scoring function: [(lat, lon, height), ...]
    candidates_list = []
    for k in range(K):
        candidates_list.append((float(lats[k]), float(lons[k]), radar_height_agl_m))

    # -----------------------------------
    # 3. Score Candidates (Optimized)
    # -----------------------------------
    # We use rank_candidates_full_grid because it loads the terrain ONLY ONCE
    # (calling score_one_radar in a loop would reload terrain N times = slow)
    print(f"\n--- Scoring {K} candidates (Full Grid Method) ---")
    
    ranked_results = rank_candidates_full_grid(
    candidates=candidates_list,
    flight_levels=flight_levels,
    terrain_npz_path=terrain_file,
    n_samples=n_samples,
    margin_m=margin_m,
    show_progress=True
)


    # -----------------------------------
    # 4. Display Top 10
    # -----------------------------------
    print("\n" + "="*60)
    print("TOP 10 CANDIDATES")
    print("="*60)
    for i, r in enumerate(ranked_results[:10], start=1):
        print(f"#{i:<2} Score: {r['score']:6.2f}% | Lat: {r['lat']:.5f}, Lon: {r['lon']:.5f}")

    # -----------------------------------
    # 5. Save Results
    # -----------------------------------
    # Extract arrays for saving
    final_lats = np.array([r['lat'] for r in ranked_results])
    final_lons = np.array([r['lon'] for r in ranked_results])
    final_scores = np.array([r['score'] for r in ranked_results])
    final_covs = np.array([r['cov_pct'] for r in ranked_results], dtype=object)

    np.savez(
        output_file,
        lat=final_lats,
        lon=final_lons,
        score=final_scores,
        cov_by_fl=final_covs
    )
    print(f"\n✓ Results saved to {output_file}")

if __name__ == "__main__":
    main()